In [24]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from pathlib import Path

root = Path('FireDepartmentCallsSelected.csv')
fire = pd.read_csv(root)
fire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315323 entries, 0 to 315322
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Call Type                             315323 non-null  object
 1   Call Date                             315323 non-null  object
 2   Received DtTm                         315323 non-null  object
 3   Dispatch DtTm                         315323 non-null  object
 4   Response DtTm                         308541 non-null  object
 5   On Scene DtTm                         255840 non-null  object
 6   Station Area                          315320 non-null  float64
 7   ALS Unit                              315323 non-null  bool
 8   Call Type Group                       313414 non-null  object
 9   Unit Type                             315323 non-null  object
 10  Location                              315323 non-null  object
 11  Neighborhooods - Analysis Boundaries  315323 non-null  object
dtypes: bool(1), float64(1), object(10)
memory usage: 26.8+ MB

In [25]:
# remove missing values
fire = fire.dropna()
print(fire.shape)
fire.head()

(254240, 12)

,Call Type,Call Date,Received DtTm,Dispatch DtTm,Response DtTm,On Scene DtTm,Station Area,ALS Unit,Call Type Group,Unit Type,Location,Neighborhooods - Analysis Boundaries
0,Structure Fire,07/25/2019,07/25/2019 07:16:45 PM,07/25/2019 07:18:47 PM,07/25/2019 07:21:12 PM,07/25/2019 07:21:39 PM,41.0,True,Alarm,ENGINE,"(37.792059516639355, -122.41694742808038)",Nob Hill
1,Structure Fire,07/25/2019,07/25/2019 07:16:45 PM,07/25/2019 07:18:47 PM,07/25/2019 07:19:14 PM,07/25/2019 07:20:43 PM,41.0,True,Alarm,ENGINE,"(37.792059516639355, -122.41694742808038)",Nob Hill
2,Structure Fire,07/25/2019,07/25/2019 07:16:45 PM,07/25/2019 07:18:47 PM,07/25/2019 07:19:29 PM,07/25/2019 07:20:26 PM,41.0,True,Alarm,ENGINE,"(37.792059516639355, -122.41694742808038)",Nob Hill
4,Structure Fire,07/25/2019,07/25/2019 07:16:45 PM,07/25/2019 07:18:47 PM,07/25/2019 07:19:32 PM,07/25/2019 07:21:57 PM,41.0,False,Alarm,TRUCK,"(37.792059516639355, -122.41694742808038)",Nob Hill
5,Structure Fire,07/25/2019,07/25/2019 07:16:45 PM,07/25/2019 07:18:47 PM,07/25/2019 07:19:20 PM,07/25/2019 07:21:54 PM,41.0,False,Alarm,TRUCK,"(37.792059516639355, -122.41694742808038)",Nob Hill

In [26]:
# check column types
fire.dtypes

Call Type                                object
Call Date                                object
Received DtTm                            object
Dispatch DtTm                            object
Response DtTm                            object
On Scene DtTm                            object
Station Area                            float64
ALS Unit                                   bool
Call Type Group                          object
Unit Type                                object
Location                                 object
Neighborhooods - Analysis Boundaries     object
dtype: object

In [27]:
# convert datetime columns from strings to datetime
fire.loc[:,['Received DtTm', 'Dispatch DtTm', 'Response DtTm', 'On Scene DtTm']] = (
    fire.loc[:, 
             ['Received DtTm', 'Dispatch DtTm', 'Response DtTm', 'On Scene DtTm']].apply(pd.to_datetime, format='%m/%d/%Y %I:%M:%S %p')
)
fire['Call Date'] = pd.to_datetime(fire['Call Date'], format='%m/%d/%Y')
fire.dtypes

Call Type                                       object
Call Date                               datetime64[ns]
Received DtTm                           datetime64[ns]
Dispatch DtTm                           datetime64[ns]
Response DtTm                           datetime64[ns]
On Scene DtTm                           datetime64[ns]
Station Area                                   float64
ALS Unit                                          bool
Call Type Group                                 object
Unit Type                                       object
Location                                        object
Neighborhooods - Analysis Boundaries            object
dtype: object

In [28]:
fire.head()

,Call Type,Call Date,Received DtTm,Dispatch DtTm,Response DtTm,On Scene DtTm,Station Area,ALS Unit,Call Type Group,Unit Type,Location,Neighborhooods - Analysis Boundaries
0,Structure Fire,2019-07-25,2019-07-25 19:16:45,2019-07-25 19:18:47,2019-07-25 19:21:12,2019-07-25 19:21:39,41.0,True,Alarm,ENGINE,"(37.792059516639355, -122.41694742808038)",Nob Hill
1,Structure Fire,2019-07-25,2019-07-25 19:16:45,2019-07-25 19:18:47,2019-07-25 19:19:14,2019-07-25 19:20:43,41.0,True,Alarm,ENGINE,"(37.792059516639355, -122.41694742808038)",Nob Hill
2,Structure Fire,2019-07-25,2019-07-25 19:16:45,2019-07-25 19:18:47,2019-07-25 19:19:29,2019-07-25 19:20:26,41.0,True,Alarm,ENGINE,"(37.792059516639355, -122.41694742808038)",Nob Hill
4,Structure Fire,2019-07-25,2019-07-25 19:16:45,2019-07-25 19:18:47,2019-07-25 19:19:32,2019-07-25 19:21:57,41.0,False,Alarm,TRUCK,"(37.792059516639355, -122.41694742808038)",Nob Hill
5,Structure Fire,2019-07-25,2019-07-25 19:16:45,2019-07-25 19:18:47,2019-07-25 19:19:20,2019-07-25 19:21:54,41.0,False,Alarm,TRUCK,"(37.792059516639355, -122.41694742808038)",Nob Hill

In [29]:
# calculate difference in total seconds between on scene time and received, dispatch, and response time
# received -> dispatch -> response -> on scene
fire['diff_received_to_dispatch'] = fire['Dispatch DtTm'] - fire['Received DtTm']
fire['diff_received_to_dispatch'] = fire['diff_received_to_dispatch'].apply(lambda x: x.total_seconds())

fire['diff_dispatch_to_response'] = fire['Response DtTm'] - fire['Dispatch DtTm']
fire['diff_dispatch_to_response'] = fire['diff_dispatch_to_response'].apply(lambda x: x.total_seconds())

fire['diff_response_to_onScene'] = fire['On Scene DtTm'] - fire['Response DtTm']
fire['diff_response_to_onScene'] = fire['diff_response_to_onScene'].apply(lambda x: x.total_seconds())

# total wait time between received calls and on scene arrival
fire['onScene_wait_time'] = fire['On Scene DtTm'] - fire['Received DtTm']
fire['onScene_wait_time'] = fire['onScene_wait_time'].apply(lambda x: x.total_seconds())
fire.head()

,Call Type,Call Date,Received DtTm,Dispatch DtTm,Response DtTm,On Scene DtTm,Station Area,ALS Unit,Call Type Group,Unit Type,Location,Neighborhooods - Analysis Boundaries,diff_received_to_dispatch,diff_dispatch_to_response,diff_response_to_onScene,onScene_wait_time
0,Structure Fire,2019-07-25,2019-07-25 19:16:45,2019-07-25 19:18:47,2019-07-25 19:21:12,2019-07-25 19:21:39,41.0,True,Alarm,ENGINE,"(37.792059516639355, -122.41694742808038)",Nob Hill,122.0,145.0,27.0,294.0
1,Structure Fire,2019-07-25,2019-07-25 19:16:45,2019-07-25 19:18:47,2019-07-25 19:19:14,2019-07-25 19:20:43,41.0,True,Alarm,ENGINE,"(37.792059516639355, -122.41694742808038)",Nob Hill,122.0,27.0,89.0,238.0
2,Structure Fire,2019-07-25,2019-07-25 19:16:45,2019-07-25 19:18:47,2019-07-25 19:19:29,2019-07-25 19:20:26,41.0,True,Alarm,ENGINE,"(37.792059516639355, -122.41694742808038)",Nob Hill,122.0,42.0,57.0,221.0
4,Structure Fire,2019-07-25,2019-07-25 19:16:45,2019-07-25 19:18:47,2019-07-25 19:19:32,2019-07-25 19:21:57,41.0,False,Alarm,TRUCK,"(37.792059516639355, -122.41694742808038)",Nob Hill,122.0,45.0,145.0,312.0
5,Structure Fire,2019-07-25,2019-07-25 19:16:45,2019-07-25 19:18:47,2019-07-25 19:19:20,2019-07-25 19:21:54,41.0,False,Alarm,TRUCK,"(37.792059516639355, -122.41694742808038)",Nob Hill,122.0,33.0,154.0,309.0

In [30]:
fire.describe()

,Station Area,diff_received_to_dispatch,diff_dispatch_to_response,diff_response_to_onScene,onScene_wait_time
count,254240.000000,254240.000000,254240.000000,2.542400e+05,2.542400e+05
mean,17.749807,159.850975,54.691292,3.174566e+02,5.319988e+02
std,14.211759,345.432074,67.325950,1.580275e+04,1.580706e+04
min,1.000000,-12136.000000,-445.000000,-7.965637e+06,-7.965518e+06
25%,5.000000,69.000000,8.000000,1.450000e+02,3.250000e+02
50%,14.000000,117.000000,40.000000,2.380000e+02,4.390000e+02
75%,32.000000,177.000000,82.000000,4.400000e+02,6.590000e+02
max,51.000000,64192.000000,5230.000000,1.675800e+04,6.517500e+04

In [33]:
"""
Remove rows where the difference is negative b/c this indicates a clerical reporting error.
We also should remove entries that have any diff_* columns containing a value of 0.
It's unrealist for a department to respond instantaneous. 
""" 
fire = fire.loc[(fire[list(fire.filter(regex='diff_*').columns)] > 0).all(axis=1), :]
fire.describe() # much better

,Station Area,diff_received_to_dispatch,diff_dispatch_to_response,diff_response_to_onScene,onScene_wait_time
count,236930.000000,236930.000000,236930.000000,236930.000000,236930.000000
mean,17.817777,146.529258,54.296189,360.853007,561.678454
std,14.199649,260.917748,51.533795,330.218526,429.096774
min,1.000000,2.000000,1.000000,1.000000,14.000000
25%,5.000000,69.000000,10.000000,154.000000,331.000000
50%,14.000000,115.000000,44.000000,247.000000,444.000000
75%,32.000000,172.000000,83.000000,451.000000,660.000000
max,51.000000,64192.000000,3001.000000,16758.000000,65175.000000

In [34]:
# check out the entries in each call type group with the largest call received to on scene wait time  
fire.groupby('Call Type Group').apply(lambda x: x.nlargest(1, columns='onScene_wait_time'))

,,Call Type,Call Date,Received DtTm,Dispatch DtTm,Response DtTm,On Scene DtTm,Station Area,ALS Unit,Call Type Group,Unit Type,Location,Neighborhooods - Analysis Boundaries,diff_received_to_dispatch,diff_dispatch_to_response,diff_response_to_onScene,onScene_wait_time
Call Type Group,,,,,,,,,,,,,,,,,
Alarm,248182,Gas Leak (Natural and LP Gases),2019-09-22,2019-09-22 01:42:53,2019-09-22 05:15:17,2019-09-22 05:16:38,2019-09-22 05:21:42,42.0,False,Alarm,ENGINE,"(37.72615765720809, -122.40157931639153)",Bayview Hunters Point,12744.0,81.0,304.0,13129.0
Fire,244527,Structure Fire,2019-09-25,2019-09-25 18:19:54,2019-09-26 03:25:51,2019-09-26 03:30:55,2019-09-26 03:55:23,17.0,False,Fire,ENGINE,"(37.73071037665978, -122.39302346957767)",Bayview Hunters Point,32757.0,304.0,1468.0,34529.0
Non Life-threatening,2670,Medical Incident,2019-10-21,2019-10-21 00:16:48,2019-10-21 18:06:40,2019-10-21 18:06:59,2019-10-21 18:23:03,43.0,True,Non Life-threatening,MEDIC,"(37.72343169188261, -122.43627316625336)",Outer Mission,64192.0,19.0,964.0,65175.0
Potentially Life-Threatening,251620,Medical Incident,2019-12-11,2019-12-11 09:46:50,2019-12-11 16:02:29,2019-12-11 16:03:35,2019-12-11 16:06:08,36.0,True,Potentially Life-Threatening,ENGINE,"(37.773523379864784, -122.42123215700101)",Mission,22539.0,66.0,153.0,22758.0

In [58]:
# fixed mispelled neighborhood column
fire = fire.rename(columns={'Neighborhoods - Analysis Boundaries': 'Neighborhoods'})
# remove any null values
fire.dropna(inplace=True)
# write filtered data to csv
# fire.to_csv('FireDepartmentCallsSelectedNAFilteredWithDiffs.csv', index=False)

In [59]:
fire.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 236930 entries, 0 to 315320
Data columns (total 16 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Call Type                  236930 non-null  object
 1   Call Date                  236930 non-null  datetime64[ns]
 2   Received DtTm              236930 non-null  datetime64[ns]
 3   Dispatch DtTm              236930 non-null  datetime64[ns]
 4   Response DtTm              236930 non-null  datetime64[ns]
 5   On Scene DtTm              236930 non-null  datetime64[ns]
 6   Station Area               236930 non-null  float64
 7   ALS Unit                   236930 non-null  bool
 8   Call Type Group            236930 non-null  object
 9   Unit Type                  236930 non-null  object
 10  Location                   236930 non-null  object
 11  Neighborhoods              236930 non-null  object
 12  diff_received_to_dispatch  236930 non-null  float64
 13  diff_dispatch_to_response  236930 non-null  float64
 14  diff_response_to_onScene   236930 non-null  float64
 15  onScene_wait_time          236930 non-null  float64
dtypes: bool(1), datetime64[ns](5), float64(5), object(5)
memory usage: 29.1+ MB

In [60]:
fire.groupby('Call Type Group').describe()

                             Station Area                                  \
                                    count       mean        std  min  25%
Call Type Group
Alarm                             51201.0  18.311283  13.797880  1.0  6.0
Fire                               6710.0  21.681073  13.506635  1.0  9.0
Non Life-threatening              62518.0  17.651300  14.214015  1.0  5.0
Potentially Life-Threatening     116501.0  17.467713  14.365285  1.0  3.0

                                               diff_received_to_dispatch  \
                               50%   75%   max                     count
Call Type Group
Alarm                         16.0  32.0  51.0                   51201.0
Fire                          20.0  34.0  51.0                    6710.0
Non Life-threatening          13.0  32.0  51.0                   62518.0
Potentially Life-Threatening  13.0  32.0  51.0                  116501.0

                                          ... diff_response_to_onScene  \
                                    mean  ...                      75%
Call Type Group                           ...
Alarm                         130.399465  ...                    236.0
Fire                          206.454844  ...                    359.0
Non Life-threatening          173.236252  ...                    766.0
Potentially Life-Threatening  135.834868  ...                    383.0

                                      onScene_wait_time              \
                                  max             count        mean
Call Type Group
Alarm                          4588.0           51201.0  418.266225
Fire                           8630.0            6710.0  625.135320
Non Life-threatening          16758.0           62518.0  781.658850
Potentially Life-Threatening   6669.0          116501.0  503.003588


                                     std   min    25%    50%    75%      max
Call Type Group
Alarm                         270.976437  56.0  303.0  372.0  460.0  13129.0
Fire                          849.691799  59.0  322.0  435.0  640.0  34529.0
Non Life-threatening          525.719040  20.0  475.0  682.0  972.0  65175.0
Potentially Life-Threatening  337.067545  14.0  313.0  414.0  578.0  22758.0

[4 rows x 40 columns]

In [61]:
# for reference: these are the columns we want to get averages for
cols = fire.filter(regex='diff_*').columns.tolist()
cols.append('onScene_wait_time')
cols

['diff_received_to_dispatch',
 'diff_dispatch_to_response',
 'diff_response_to_onScene',
 'onScene_wait_time']

In [62]:
avg_wait_times = fire.groupby(by=['Call Type Group', 'Neighborhoods']).agg(**{
    'Avg Received to Dispatch Wait Time': ('diff_received_to_dispatch', lambda x: x.mean()/60),
    'Avg Dispatch to Response Wait Time': ('diff_dispatch_to_response', lambda x: x.mean()/60),
    'Avg Response to On Scene Wait Time': ('diff_response_to_onScene', lambda x: x.mean()/60),
    'Avg On Scene Wait Time': ('onScene_wait_time', lambda x: x.mean()/60),
    
}).reset_index()
avg_wait_times.head()

,Call Type Group,Neighborhoods,Avg Received to Dispatch Wait Time,Avg Dispatch to Response Wait Time,Avg Response to On Scene Wait Time,Avg On Scene Wait Time
0,Alarm,Bayview Hunters Point,2.556519,1.517234,4.341844,8.415596
1,Alarm,Bernal Heights,2.249301,1.359975,3.830157,7.439432
2,Alarm,Castro/Upper Market,1.993099,1.353858,3.213993,6.560950
3,Alarm,Chinatown,2.313490,1.465307,2.786495,6.565293
4,Alarm,Excelsior,2.408596,1.380050,4.179649,7.968296

In [63]:
avg_wait_times.describe()

,Avg Received to Dispatch Wait Time,Avg Dispatch to Response Wait Time,Avg Response to On Scene Wait Time,Avg On Scene Wait Time
count,168.000000,168.000000,168.000000,168.000000
mean,2.726311,1.078536,6.164184,9.969031
std,0.868743,0.300200,2.382192,2.789405
min,1.695430,0.534610,2.786495,5.775521
25%,2.238971,0.802595,4.158691,7.778505
50%,2.462679,1.095816,5.585926,9.023732
75%,2.945755,1.338655,8.147857,12.095812
max,7.206306,1.694540,11.964286,18.128736

In [64]:
# save results to csv
avg_wait_times.to_csv('avg_wait_times_by_call_type_neighborhood.csv', index=False)